### PR TITLE
Add air units and mobile flak unit

### LINKED ISSUE #83: Add air units
#67 
This requires changes to the way bases are handled in the rules and schema.

### PR DESCRIPTION
**Pull request by tbeddy**
Closes #83 

This PR builds off #87, mostly just adding the data and assets for four more units (bomber, fighter, gunship, mobile flak) and a base-type (airfield).

When adding the stats table to the unit-picker modal, I decided to use the first letter of each armor-type to conserve space. However, now that "Air" joins "Armored," I decided to change their shortened forms to "Ai" and "Ar," respectively. I don't think this looks very good and it should probably be changed, but I'm not sure to what.

### CODE REVIEW

**Comment by tbeddy** [comment]
@djwhitt Feedback?

**Comment by djwhitt** [comment]
Sorry for sitting on this one so long. I'll take a look in the next few days.

**Comment by tbeddy** [comment]
Would changing any of the unit-type names (personnel, armored, naval, air) be a bad idea? I'm not very familiar with war-game terminology and don't know if that would break with standard naming conventions. If it does, I'd rather just keep "Ai" and "Ar."

**Comment by djwhitt** [comment]
I'd say leave the unit type names for now. The abbreviations aren't ideal, but I think what we really want is a different unit picker design. The giant table is a getting a bit unwieldy.

**Pull request merged**
