### PR TITLE
Display coordinates of tile mouse is hovering over

### LINKED ISSUE #23: Display coordinates when mouse moves over tiles
Currently thinking coordinates (and other details) should be displayed in a status area under the map.

### PR DESCRIPTION
**Pull request by tbeddy**
Closes #23

### CODE REVIEW

**Comment by tbeddy** [comment]
Would it be better not to display this when on mobile?

**Comment by djwhitt** [comment]
Yes, we should probably hide this on small screens.

**Comment by djwhitt** [comment]
Logic looks good. See my comment on #90 re formatting.

**Comment by tbeddy** [comment]
Would you prefer that nothing show up when no tile is being hovered over instead of "Hover: none"?

**Comment by tbeddy** [comment]
I like having "none" there because otherwise, if you quickly move the mouse in and out of the map, the footer is constantly shifting and I think it looks bad.

**Comment by djwhitt** [comment]
In what order are you displaying stats and hover text? I'd put hover last so things don't shift around when it disappears. Assuming that works, I'd prefer it hidden when not hovering over a tile.

**Comment by tbeddy** [comment]
I'm doing stats then hover, as you suggested. But if no tiles are selected, no stats will be displayed, so won't the shifting still happen?

**Comment by tbeddy** [comment]
By shifting, I'm referring to the footer moving up and down
footer

**Comment by djwhitt** [comment]
Ah, I thought you were talking about left/right shifting. I'd always display placeholder for Selected and Targeted even when nothing is selected or targeted, like this: "Selected: – • Targeted: –". That would get rid of vertical shifting. I suppose it's probably good to do the same with hover for consistency. I was initially thinking it would be nice to reduce clutter by hiding it since discoverability isn't an issue for that functionality.

**Comment by tbeddy** [comment]
Is there anything else you'd like me to do for this or #90 ?

**Comment by djwhitt** [comment]
Nope, looks good. Merged.

**Pull request merged**
