### PR TITLE
Display terrain effects for selected and targeted terrains

### LINKED ISSUE #55: Display terrain effects for selected and targeted terrains
Should display movement cost, attack bonus, and defense bonus.

### PR DESCRIPTION
**Pull request by tbeddy**
Closes #55
The terrain effects are displayed underneath the map in a small Bootstrap table.
pic

### CODE REVIEW

**Comment by djwhitt** [comment]
The logic looks good, but the format needs to be more compact. Selected, targeted, and hover information should all appear on one line. Also, though it wasn't in the original description, I think we should also display the selected and targeted coordinates. I'm imagine something like this: "Selected: Q,R (M,AT,AR) • Targeted: Q:R (M,AT,AR) • Hover: Q,R" with hover text for each group of stats describing what the fields mean (e.g. "Q:X, R:Y, Movement Cost:Z ...").

**Comment by tbeddy** [comment]
Should there be some text that explains the information? If a user sees "Selected: 2,2 (3,0,0)", they might be able to figure out what "2,2" means, but "3,0,0" isn't very clear.

**Comment by djwhitt** [comment]
I'd give them some hover text with descriptions of each value, similar to the abbreviations in the build modal.

**Comment by tbeddy** [comment]
Woops, I somehow missed your hover text comment in the previous comment. Sorry about that.

**Comment by djwhitt** [comment]
I'm good with merging this after the conflicts are resolved.

**Comment by tbeddy** [comment]
Done

**Pull request merged**
